---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/agent

inputs:
- name: bosh-agent
- name: bosh-agent-ci
- name: version-semver

params: {}

run:
  path: bosh-agent-ci/ci/tasks/assert-version-aligns.sh
