---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/agent
    tag: latest

inputs:
- name: bosh-agent
- name: version-semver

outputs:
- name: compiled-linux-amd64

params:
  OUTPUT_DIR: compiled-linux-amd64
  GOARCH: amd64
  GOOS:   linux

run:
  path: bosh-agent/ci/tasks/build.sh
