---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/agent

inputs:
- name: bosh-agent
- name: bosh-agent-ci
- name: version-semver

outputs:
- name: compiled-windows-amd64

params:
  OUTPUT_DIR: compiled-windows-amd64
  GOARCH: amd64
  GOOS:   windows

run:
  path: bosh-agent-ci/ci/tasks/build.sh
