---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/agent
    tag: latest

inputs:
- name: bosh-agent
- name: bosh-agent-ci

run:
  path: bosh-agent-ci/ci/tasks/test-unit.sh
